---
- name: Install node_exporter for infra nodes
  hosts: infra-host
  roles:
    - node_exporter_role
- name: Install node_exporter for K8S nodes (PROD)
  become: true
  hosts: cp1
  vars:
    helm_version: "3.6.0"
    helm_dir: "/tmp"
  tasks:
    - name: Download HELM (PROD)
      become: true
      get_url:
        url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
        dest: "/tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false
    - name: Unpack helm
      become: true
      unarchive:
        src: "{{ helm_dir }}/helm-v{{ helm_version }}-linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "{{ helm_dir }}/helm-v{{ helm_version }}"
        remote_src: yes
      check_mode: false
    - name: Copy Helm binaries
      become: true
      copy:
        src: "{{ helm_dir }}/linux-amd64/helm"
        dest: "/usr/local/bin/helm"
        mode: 0775
        remote_src: yes
    - name: Copy bash file
      become: true
      copy:
        src: "files/helm-prod.sh"
        dest: "{{ helm_dir }}"
        mode: 0755
    - name: Run script
      become: true
      shell:
        cmd: "helm-prod.sh"
        chdir: "{{ helm_dir }}/"
