---
- name: Install node_exporter for infra nodes
  hosts: infra-host
  roles:
    - node_exporter_role
- name: Install node_exporter for K8S nodes (PROD)
  become: true
  hosts: cp1
  tasks:
    - name: Install HELM + node_exporter (PROD)
      become: true
      roles:
        - helm_role
    - name: Copy bash file
      become: true
      copy:
        src: "files/helm-prod.sh"
        dest: "/tmp"
      remote_src: yes
      mode: 0755
    - name: Run script
      become: true
      script:
        cmd: /tmp/helm-prod.sh
      remote_src: yes
