---
- name: Install node_exporter for infra nodes
  hosts: infra-host
  roles:
    - node_exporter_role
- name: Install node_exporter for K8S nodes (PROD)
  become: true
  hosts: cp1
  tasks:
    - name: Download HELM (PROD)
      become: true
      get_url:
        url: "https://get.helm.sh/helm-v{{ helm_verion }}-linux-amd64.tar.gz"
        dest: "/tmp/helm-v{{ helm_verion }}-linux-amd64.tar.gz"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false
    - name: Unpack helm
      become: true
      unarchive:
        src: "/tmp/helm-v{{ helm_verion }}-linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/helm-v{{ helm_verion }}"
      check_mode: false
    - name: Copy Helm binaries
      become: true
      copy:
        src: "/tmp/helm-v{{ helm_verion }}/linux-amd64/helm"
        dest: "/usr/local/bin/helm"
        mode: 0775
        remote_src: yes
    - name: Copy bash file
      become: true
      copy:
        src: "files/helm-prod.sh"
        dest: "/tmp"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755
    - name: Run script
      become: true
      script:
        cmd: "./tmp/helm-prod.sh"
      remote_src: yes
