---
- name: node_exporter_role
  src: git@github.com:cloudalchemy/ansible-node-exporter.git
  scm: git
  version: "2.0.0"
- name: helm_role
  src: git@github.com:gantsign/ansible_role_helm.git
  scm: git
  version: "2.12.0"