---
- name: node_exporter_role
  src: git@github.com:cloudalchemy/ansible-node-exporter.git
  scm: git
  version: "2.0.0"
- name: helm_role
  src: git@github.com:Flaconi/ansible-role-helm.git
  scm: git
  version: "v1.0.0"
