---
- name: Install node_exporter for K8S nodes (STAGE)
  become: true
  hosts: cp1
  tasks:
    - name: Install HELM (STAGE)
      become: true
        roles:
          - helm_role
    - name: Install node_exporter helm-chart
      become: true
         tasks:
           - name: Copy bash file
             copy:
               src: "files/helm-stage.sh"
               dest: "/tmp"
               remote_src: yes
               mode: 0755
           - name: Run script
             script:
               cmd: /tmp/helm-prod.sh
               remote_src: yes
